### ISSUE TITLE
docker-compose up doesnt play nice with elastic

### ISSUE THREAD

**Issue by buzzdan** [mhilker/cspr-collector#5]
i tried running `docker-compose up` and saw some logs in the cspr-collector container but none ever reached elastic
i changed the docker-compose.yml to work against elastic as mentioned in the readme:

```
  cspr-collector:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: --host 0.0.0.0:8080 -output-es
    image: mhilker/cspr-collector
    ports:
      - 8080:8080
```
but still none worked

BTW: i tried POSTing to elastic myself and it did work as i found my doc via kibana
so i believe there only a problem in the wiring between the collector and elastic...

any insights will be hightly appriciated

thanks a lot!
:-Dan

**Comment by mhilker** [comment]
Hey, thanks for your feedback.

It seems there the hostname option inside the provided `docker-compose.yml` is missing.

Please try to add `-output-es-host "http://elasticsearch:9200/"` at the end of your command and see if it works.

**Comment by buzzdan** [comment]
@mhilker yes it is working
here's the working version:

```
cspr-collector:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: --host 0.0.0.0:8080 -output-es -output-es-host "http://elasticsearch:9200/"
    image: mhilker/cspr-collector
    ports:
      - 8080:8080

```
